name: Dagger Build & Push to GHCR

on:
  push:
    branches: [ master ]

jobs:
  dagger:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install dagger-io anyio

      - name: Run Dagger pipeline
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_PAT: ${{ secrets.GHCR_PAt }} # You already added this
        run: python3 main.py
